apiVersion: v1
kind: Template
metadata:
  name: proxy
objects:
- apiVersion: v1
  data:
    proxy.conf: |
      cache_peer proxy.${PROJECT_NAME}-ops.svc.cluster.local parent 8080 0 no-query default
      never_direct allow all
      http_access allow all
  kind: ConfigMap
  metadata:
    name: proxy
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: proxy
    name: proxy
  spec:
    replicas: 1
    selector:
      app: proxy
      deploymentconfig: proxy
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: proxy
          deploymentconfig: proxy
      spec:
        containers:
        - image: 10.204.242.20:5000/ops/squid:latest
          imagePullPolicy: Always
          name: proxy
          ports:
          - containerPort: 3128
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /etc/squid/conf.d/
            name: conf
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            name: proxy
          name: conf
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - proxy
        from:
          kind: ImageStreamTag
          name: squid:latest
          namespace: ops
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: proxy
    name: proxy
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 3128
    selector:
      app: proxy
      deploymentconfig: proxy
    sessionAffinity: None
    type: ClusterIP
